### PR TITLE
Create autoconfig.php.jinja

### PR DESCRIPTION
**Pull request by andrei821**
Create autoconfig jinja template

### CODE REVIEW

**Comment by gravyboat** [comment]
Is there any reason the host, directory, and database type aren't configurable?

**Comment by neuhalje** [comment]
@andrei821: I was unable to find the documentation for autoconfig.php in the [owncloud documentation](https://doc.owncloud.org/search.html?q=autoconfig.php#). Is this some debian specific configuration?

**Comment by andrei821** [comment]
@neuhalje autoconfig.php is owncloud specific. you can find it here: https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/automatic_configuration.html#automatic-configurations-examples

**Comment by neuhalje** [comment]
@andrei821 Thanks a lot

**Comment by alxwr** [comment]
Management of `autoconfig.php` was implemented in a1266396.

**Comment by alxwr** [comment]
@andrei821 Sry, apparently I missed this PR back in 2017. If you are still missing a feature from this PR please explain which one (and reopen the PR).

**Pull request closed without merging**
